name: R12 Marketing
favicon: null
layout_spectrum: 0.77167
typography_spectrum: 0.7851544939912856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0071bc'
    - '#e6e6e6'
    - '#1cb5f8'
    - '#808080'
    - '#001d1b'
  brandStrength: 0.9375
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
